### ISSUE TITLE
No stats shown and screen wrong rotation

### ISSUE THREAD

**Issue by wpa-2** [dubbadhar/piHoleLCDStat#1]
First off thanks for this project its awesome, i have needed something for my spare screen. 

Linux  4.19.97-v7+

Waveshare 3.2 LCD 

1. I am not receiving any stats from pihole at all everything it's on 0 apart from the pi stats ie ram, cpu, disk,temp 

2. The script is only using half of the screen, the Raspbian desktop is fine so its installed correctly. 

Have tried to change the config file but doesn't seem to change anything at all.

**Comment by rnayabed** [comment]
1. Check whether your pi hole is allowing usage and api access. It usually gives you a choice during installation, but I believe you can change it later in settings (the pihole web admin page)

2. Run './piHoleLCDStat_edit_config' in the piholelcdstat directory. 

If your screen is in portrait mode, make Screen Height as '320' and Screen Width as '240'

If your screen is in landscape mode, make Screen Height as '240' and Screen Width as '320'

**Comment by wpa-2** [comment]
Thanks for getting back to me, i tried switching screen heights but it never goes into portrait mode.

As for api settings does this look good? 
![vvv](https://user-images.githubusercontent.com/9049886/79062893-e8725600-7c95-11ea-82fc-16aa4fc2be6e.png)

After further checking the api is defo working 
http://pi.hole/admin/api.php?status >>> Returns {"status":"enabled"}

**Comment by rnayabed** [comment]
What is your screen orientation? Also would you mind sharing `config` of the piHoleLCDStat?

**Comment by rnayabed** [comment]
also share `/boot/config.txt` of your raspberry pi. Waveshare apparently makes the default resolution 480x320 when it should be the 320x240

**Comment by wpa-2** [comment]
Config.txt
`# For more options and information see
# http://www.raspberrypi.org/documentation/configuration/config-txt.md
# Some settings may impact device functionality. See link above for details

# uncomment if you get no picture on HDMI for a default "safe" mode
#hdmi_safe=1

# uncomment this if your display has a black border of unused pixels visible
# and your display can output without overscan
#disable_overscan=1

# uncomment the following to adjust overscan. Use positive numbers if console
# goes off screen, and negative if there is too much border
#overscan_left=16
#overscan_right=16
#overscan_top=16
#overscan_bottom=16

# uncomment to force a console size. By default it will be display's size minus
# overscan.
#framebuffer_width=1280
#framebuffer_height=720

# uncomment if hdmi display is not detected and composite is being output
hdmi_force_hotplug=1

# uncomment to force a specific HDMI mode (this will force VGA)
#hdmi_group=1
#hdmi_mode=1

# uncomment to force a HDMI mode rather than DVI. This can make audio work in
# DMT (computer monitor) modes
#hdmi_drive=2

# uncomment to increase signal to HDMI, if you have interference, blanking, or
# no display
#config_hdmi_boost=4

# uncomment for composite PAL
#sdtv_mode=2

#uncomment to overclock the arm. 700 MHz is the default.
#arm_freq=800

# Uncomment some or all of these to enable the optional hardware interfaces
dtparam=i2c_arm=on
#dtparam=i2s=on
dtparam=spi=on
enable_uart=1
# Uncomment this to enable the lirc-rpi module
#dtoverlay=lirc-rpi

# Additional overlays and parameters are documented /boot/overlays/README

# Enable audio (loads snd_bcm2835)
dtparam=audio=on
dtoverlay=waveshare32b:rotate=270
#dtoverlay=ads7846,cs=1,penirq=17,penirq_pull=2,speed=1000000,keep_vref_on=1,swapxy=0,pmax=255,xohms=60,xmin=200,xmax=3900,ymin=200,ymax=3900
hdmi_force_hotplug=1
#max_usb_current=1
hdmi_group=2
hdmi_mode=1
hdmi_mode=87
hdmi_cvt 480 320 60 6 0 0 0
hdmi_drive=2`

config from in the piHoleLCDStat folder
`true::false::5000::10000::30000::192.168.0.100::12589::320.0::240.0::15.0::#4caf50::#d81b60::5::5::5::user@host` 
I changed user an host of course.

**Comment by rnayabed** [comment]
`hdmi_cvt 480 320 60 6 0 0 0`

As i suspected, its waveshare's fault for setting the resolution to 480x320 when it should be 320x240

change `hdmi_cvt 480 320 60 6 0 0 0` to `hdmi_cvt 320 240 60 6 0 0 0`

**Comment by rnayabed** [comment]
This is why i dont recommend using these cheap Chinese built screens (Even tho i use one personally :P)

**Comment by wpa-2** [comment]
Right screen is setup fine now, Its on landscape now which is fine but how would i change it to portrait ? 

Any idea why i'm not getting stats?

**Comment by dubbadhar** [comment]
I just tried it on my end, works perfectly fine, with the latest variant.
Could you backup your blacklists, then reinstall pi hole?

**Comment by dubbadhar** [comment]
Ok wait

**Comment by rnayabed** [comment]
change
```
true::false::5000::10000::30000::192.168.0.100::12589::320.0::240.0::15.0::#4caf50::#d81b60::5::5::5::
```
to
```
true::false::5000::10000::30000::127.0.0.1::4711::320.0::240.0::15.0::#4caf50::#d81b60::5::5::5::
```

Im assuming that you're using running Pi-Hole in the same host as this app

**Comment by wpa-2** [comment]
Right since doing that, my screen has messed up again and i'm getting like 8 screens after tough but 3 are blank. 

Yes pi-hole is on same network. 

Might try a full reinstall of pi-hole and raspbian an get back to you.  They are on different pi's and not user  pi either not sure if that matter's/

**Comment by rnayabed** [comment]
When youre setting up `piHoleLCDStat`, just dont change the ip and port settings

**Comment by rnayabed** [comment]
@zerocolTHS were you able to fix the issue?

**Comment by rnayabed** [comment]
Closing as no responses received. You may reopen if you encounter this error again

**Comment by wpa-2** [comment]
I did do a full reinstall on both devices, managed to get screen size working fine but sadly still no stats are shown on my pi. 

I'm at a loss honestly.
