### ISSUE TITLE
No stats Shown on screen 

### ISSUE THREAD

**Issue by wpa-2** [dubbadhar/piHoleLCDStat#2]
I have tried all the other suggestion's in the other thread #1  but cannot open it so started a new one. 

My Config file

`false::false::5000::10000::30000::192.168.0.100::4711::240.0::320.0::15.0::#4caf50::#d81b60::5::5::5::`

I also tried 
`false::false::5000::10000::30000::172.0.0.1::4711::240.0::320.0::15.0::#4caf50::#d81b60::5::5::5::`

Linux version
Raspbian 4.19.97-v7+

**Comment by rnayabed** [comment]
It seems that FTL cannot be accessed outside the host by default, can you ask Pi-Hole people? perhaps their reddit (its very active and helpful) or email?

**Comment by rnayabed** [comment]
Also, are you running `piHoleLCDStat` and Pi-Hole on the same machine?

**Comment by wpa-2** [comment]
Its on a different PI but there on same network, o'k i will see if anything on the pi-hole page. 

Couldn't you add something in the code to use the API code form Pi-hole>

**Comment by rnayabed** [comment]
Can you ask them how to access the new FTL API (not the old JSON one) from
different computers in the same network?

**Comment by PromoFaux** [comment]
Currently not possible, though some work is planned for FTL 6.0 that should rectify this:

https://github.com/pi-hole/FTL/tree/new/http

edit: PR https://github.com/pi-hole/FTL/pull/659

**Comment by rnayabed** [comment]
great! glad to see it will be possible in the future

**Comment by wpa-2** [comment]
I guess we might as well close this until thing's change, Many thanks for the project.

**Comment by rnayabed** [comment]
Sure. If you have any other problems, I can help :)
